### ISSUE TITLE
Translation status in README

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/qps#328] opened 2021-08-07 17:07 UTC
The image on https://translate.lxqt-project.org/widgets/lxqt-desktop/-/qps/multi-auto.svg takes a long time to be generated.
```
pavel@MacBook-Air RandD % time curl https://translate.lxqt-project.org/widgets/lxqt-desktop/-/qps/multi-auto.svg -o multi-auto.svg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17571  100 17571    0     0   4916      0  0:00:03  0:00:03 --:--:--  4914
curl  -o multi-auto.svg  0,02s user 0,01s system 0% cpu 3,590 total
```
The same happens when it is called from GitHub server (it works as a proxy for all images you find in md files).
```
pavel@MacBook-Air RandD % curl https://camo.githubusercontent.com/27c18f7a7e360cbb01c5a7c74821bf33eae3fbd06c0cd41ff3fffc0b34ee0405/68747470733a2f2f7472616e736c6174652e6c7871742d70726f6a6563742e6f72672f776964676574732f6c7871742d6465736b746f702f2d2f7170732f6d756c74692d6175746f2e737667
Error Fetching Resource
```
Since we cannot manipulate timeout on GitHub, maybe we should either get rid of the image or optimize caching/server?
Safari:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/19782228/128608273-7723bf18-7cb6-4ecd-989b-e02c34cde238.png">
Firefox:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/19782228/128608283-29b6557c-8016-4451-b2cd-5ff20faa9354.png">

**Comment by shlyakpavel** [comment] 2021-08-07 17:08
BTW the issue also applies to QTerminal and other repos

**Comment by tsujan** [comment] 2021-08-07 17:14
It appeared instantly here, and also in https://github.com/lxqt/qterminal. Probably, it depends on other factors.

**Comment by shlyakpavel** [comment] 2021-08-07 17:25
@tsujan did you load a cached version from GitHub or directly from translate.lxqt-project.org?

**Comment by tsujan** [comment] 2021-08-07 17:38
Both.

**Comment by shlyakpavel** [comment] 2021-08-07 17:40
<img width="964" alt="image" src="https://user-images.githubusercontent.com/19782228/128609213-9b91bf3a-db8d-4406-a712-70dc06497bfa.png">
It is cached then I load it with Czech IP and it is not cached then I load it from Russia. Strange!

**Comment by shlyakpavel** [comment] 2021-08-07 17:42
It is now cached with any IP
Perhaps something changes on the server in time. You can close the issue if you find it not important

**Comment by stefonarch** [comment] 2021-08-07 17:46
Cannot reproduce at all too. 
Rarely there was a server error "connection closed" or similar but I don't have  no actual one to verify.

**Comment by tsujan** [comment] 2021-08-07 17:46
I remember that, last year, it was slow for me too. It may be related to the server.

Closing this because it isn't an issue in qps.

**Closed by tsujan** 2021-08-07 17:46 UTC

**Comment by stefonarch** [comment] 2021-08-08 04:15
> Weblate could not fetch upstream changes when updating the repository.
>fatal: unable to access 'https://github.com/lxqt/qps/': Could not resolve host: github.com
 (128)

this was yesterday at  the time of the issue
