### ISSUE TITLE
Memory leak on some desktop environments

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/qps#150] opened 2019-08-27 11:48 UTC
In less than 19 minutes it can take more memory than gnome shell
<img width="912" alt="image" src="https://user-images.githubusercontent.com/19782228/63768712-a3054200-c8d9-11e9-9013-8bf8200dd30d.png">
https://github.com/lxqt/qps/pull/149 helped a little, but there is still a huge leak left somewhere else.
My proposal is to track everything regarding the leaks here.

**Comment by tsujan** [comment] 2019-08-27 11:58
Under Linux+LXqt, it's only 22 MiB after 2 hours. I'll continue using it...

> My proposal is to track everything regarding the leaks here.

Definitely.

**Comment by shlyakpavel** [comment] 2019-08-27 12:01
> Under Linux+LXQt, it's only 22 MiB after 2 hours. I'll continue using it...
Did you try changing update period to 1ms? :D

**Comment by tsujan** [comment] 2019-08-27 12:05
For real usage? No. I set it to 500ms and lest in in the systray.

But I tested with 10ms while making the patch. I saw a "leak" but it stopped at ~20 MiB. I removed the graph as icon and it stopped at the beginning. So, IMO, it was about how `setIcon` works in Qt (for systray and the main window).

**Comment by tsujan** [comment] 2019-08-27 12:08
Please remove `trayicon->setIcon(*pm);` and `setWindowIcon(*pm);` from `Qps::set_load_icon()` and test again! That might make it easier to find the cause.

**Comment by shlyakpavel** [comment] 2019-08-27 13:14
https://programmersexception.blogspot.com/2019/04/memory-leak-con-qicon-en-qt-594-y.html
This guy states that QIcon(qpixmap) solves the problem. Moreover, according to https://doc.qt.io/qt-5/qicon.html it's us who use qicon in inproper way. I will dig it deeper  in the evening

**Comment by shlyakpavel** [comment] 2019-08-27 13:24
In other words
We make qpixmap pointer, use it in qicon, it is being copied. When the qpixmap is copied, qicon is correctly used and destroyed. QPixmap is left in the memory.

**Comment by tsujan** [comment] 2019-08-27 13:26
> This guy states that QIcon(qpixmap) solves the problem.

I'd tried it to no avail but please test it.

> it's us who use qicon in inproper way.

I haven't seen such a usage of QIcon anywhere else but I don't think it's wrong.

> We make qpixmap pointer,

I'd changed that by changing a few functions (I mean I removed the pointer) but it made no difference.

**Comment by tsujan** [comment] 2019-08-27 13:29
BTW, here, the memory usage is 28 MiB now (after ~4 hours).

**Comment by tsujan** [comment] 2019-08-27 14:56
OK, it really stopped at 28 MiB (qps shows 28 and gnome-system-monitor shows 28.4 for an hour; I checked several times) — which is very good because I'd opened some of its dialogs.

So, there's no (detectable) memory leak here.

Why it uses so much memory under gnome-shell, I have no idea but memory usage isn't determined by a single factor.

**Comment by shlyakpavel** [comment] 2019-08-27 16:03
> Linux+LXQt

Tested here on fresh Lubuntu, it's the same as it was on Gnome
> Please remove `trayicon->setIcon(*pm);` and `setWindowIcon(*pm);` from `Qps::set_load_icon()` and test again! That might make it easier to find the cause.

The leak has gone this way!

**Comment by shlyakpavel** [comment] 2019-08-27 16:11
29mb in a couple of minutes (git master on LXQt)
<img width="832" alt="image" src="https://user-images.githubusercontent.com/19782228/63788502-47997b00-c8fe-11e9-94c3-fd3a0f8a348d.png">

**Comment by tsujan** [comment] 2019-08-27 16:15
Here, it's still 28 MiB — more precisely, 28.4. I'm starting to trust this app :) It can be left in systray without problem. *No memory leak at all*.

We should see what's the difference between our use cases. One thing is your 1-ms update interval. I think even 250 ms is too short for a real use case and we should correct that spin-box.

Other things can be gnome or even the virtual machine (I use it with the real computer).

**Comment by shlyakpavel** [comment] 2019-08-27 16:22
> Other things can be gnome

Looks much like that
> or even the virtual machine (I use it with the real computer).

It stops at 29Mib on the same VM with LXQt so it's not the point

**Comment by tsujan** [comment] 2019-08-27 16:24
> It stops at 29Mib on the same VM with LXQt so it's not the point

Oh, I didn't see your other comment. Good!

Please close this if you agree with me that there's no leak.

**Comment by tsujan** [comment] 2019-08-27 16:26
Ha ha.... Gnome is the most nonstandard DE. It even doesn't have a systray.

**Comment by shlyakpavel** [comment] 2019-08-27 16:27
> Please close this if you agree with me that there's no leak.

Is it possible that leak on gnome is a qps fault?

**Comment by tsujan** [comment] 2019-08-27 16:27
I really doubt that. But there's no harm in leaving this open.

**Comment by shlyakpavel** [comment] 2019-08-27 16:29
> It even doesn't have a systray.

But QPS has a tray icon on gnome anyway (look at my screenshot)...

**Comment by tsujan** [comment] 2019-08-27 16:31
That's not the tray icon; it's the window icon. Gnome doesn't have a tray anymore -- at least, not its latest version. I won't be surprised if they remove the panel, icons, texts and everything after a few years ;)

**Comment by agaida** [comment] 2019-08-27 16:33
Gnome has no default tray handling anymore - it is now a more or less (to be honest less) working plugin that provided a systray - The reason why it work in Ubuntu: They don't released with the latest Gnome exactly for that reason - damn, @tsujan was faster :sunglasses:

**Comment by shlyakpavel** [comment] 2019-08-27 16:33
> That's not the tray icon; it's the window icon. 
Right top corner. It's a tray icon. Qt apps show their icons on gnome (at least on my ubuntu and fedora)

**Comment by tsujan** [comment] 2019-08-27 16:35
A gnome-shell extension, probably. It'll break with the next Gnome update.

**Comment by shlyakpavel** [comment] 2019-08-27 16:35
@agaida could you please answer my issue about Russian translation?

**Comment by shlyakpavel** [comment] 2019-08-27 17:12
<img width="912" alt="image" src="https://user-images.githubusercontent.com/19782228/63792716-ce525600-c906-11e9-8df2-3ed8d2647d4b.png">
LXDE shows the same thing as gnome

**Comment by tsujan** [comment] 2019-08-27 17:23
> It's a qps bug.

I'm not sure at all. It can be caused by the Qt icon-engine used in GTK environments -- I don't know what it is.

I have Gnome on my other laptop; will test under it later.

**Comment by tsujan** [comment] 2019-08-28 06:08
@plonibarploni If you open a bug report at LXQt, please avoid general and vague descriptions like the above one.

**Comment by tsujan** [comment] 2019-08-28 07:44
@shlyakpavel I tested with gnome-shell 3.32.2+11 under Manajro (almost Arch) minutes ago:  qps's memory usage stopped at 25 MiB when I gave it a 10-ms update interval. gnome-system-monitor showed the same number.

I'm afraid the cause of your problem should be somewhere else (I suspect the virtual machine).

**Comment by shlyakpavel** [comment] 2019-08-28 09:25
> I'm afraid the cause of your problem should be somewhere else (I suspect the virtual machine).

Then I'll try to install linux on my Mac natively. Seems to be challenging, tough
> EDIT: Who knows? The cause may be in older Gnome versions too.

But lxde was also affected!

**Comment by shlyakpavel** [comment] 2019-08-28 10:41
![Screenshot from 2019-08-28 10-39-19](https://user-images.githubusercontent.com/19782228/63848827-24171480-c980-11e9-829b-de827ad09a85.png)
A very real screenshot on my very real machine showing a very real leak. And also showing that qps is not ready for hidpi

**Comment by tsujan** [comment] 2019-08-28 13:39
> The issue is by no way related to VM

Then, you should find to what it is related. As I said, it's not reproducible here, with 2 laptops and under 2 different DEs.

**Comment by tsujan** [comment] 2019-08-28 14:00
> And also showing that qps is not ready for hidpi

No it isn't because no one set `Qt::AA_UseHighDpiPixmaps` to `true` for it:

![qps](https://user-images.githubusercontent.com/981076/63862093-454c2500-c9c1-11e9-9b4b-22c3e0f5da0c.png)

As I mentioned elsewhere, the GUI needs rewriting; the widgets and icons are nonstandard.

**Comment by tsujan** [comment] 2019-08-28 15:45
@shlyakpavel 

To make sure that this is about Qt's pixmap cache and not a leak, I set:

```c++
QPixmapCache::setCacheLimit(1);
```

at the beginning of `Qps` c-tor (in `qps.cpp`). The memory usage didn't change from start (10 MiB).

You could test that in the DEs where you think there's a memory leak.

**Comment by shlyakpavel** [comment] 2019-08-29 19:24
> > Please remove `trayicon->setIcon(*pm);` and `setWindowIcon(*pm);` from `Qps::set_load_icon()` and test again! That might make it easier to find the cause.
> 
> The leak has gone this way!

No, no and no. This doesn't help here on GNOME. Something else causes the leak

**Comment by shlyakpavel** [comment] 2019-08-29 19:52
I'm now 100% sure that `return QSystemTrayIcon::isSystemTrayAvailable();` in `TrayIcon::hasSysTray()` causes the leak. If I replace it with "return true" or "return false" everything is fine. Perhaps we should call it once the program is started and then store the value instead of calling it on every refresh. Where to file a bug for it?)

**Comment by tsujan** [comment] 2019-08-29 20:07
That may be a bug in the Qt plugins of those DEs (with the versions you have) because `isSystemTrayAvailable` shouldn't cause any memory leak but yes, there's no need to call `hasSysTray` continuously, especially when calling it once fixes the memory leak you see.

However, it's preferable to wait for systray at startup, in the way FeatherNotes does it -- as far as remember, I implemented in LXQt notifications too.

**Closed** 2019-08-29 20:30 UTC
