### ISSUE TITLE
Process list goes blank

### ISSUE THREAD

**Issue by danhermann** [lxqt/qps#251] opened 2020-08-31 18:27 UTC
##### Expected Behavior
QPS displays process list along with charts.

##### Current Behavior
The process list in QPS goes blank (see screen shot below) and the process counter displays 0, usually after ~5 minutes. The same thing happens whether the "thread" box is checked or not or whether I'm running from the local console or over X11. Nothing is printed to either stdout or stderr at the point that the process list goes blank. The remainder of the displayed charts (CPU, memory, uptime, etc) appear to continue working.

![qps_screenshot](https://user-images.githubusercontent.com/22777892/91753010-d6ce1400-eb8c-11ea-9394-a4e9e3a22021.png)

##### Steps to Reproduce (for bugs)
Invoke `qps &` from a terminal. Wait ~5 minutes.

##### Context
I can no longer use QPS to see what process is pegging my CPU or memory, etc.

##### System Information
* Distribution & Version: Lubuntu 20.04.1
* Kernel: 5.4.0-42
* Qt Version: 5.12.8
* lxqt-build-tools Version: 
* Package version: 
* Running on a second-generation Thinkpad P1

**Comment by tsujan** [comment] 2020-08-31 19:06
Not reproducible.

Please add a comment when you get the latest release (2.1.0) because Ubuntu 20.04 doesn't have it.

**Comment by tsujan** [comment] 2020-09-02 17:01
I forgot to mention this in my previous comment:

We've never encountered a blank view with older versions either, so we haven't done anything about it. Therefore, if it happens with 2.1.0, there should be a *hidden factor* — something that's different in your system — and we (you and I and, probably, other devs) will need to find it for us to be able to reproduce the issue in the first place.

Hence, the "question" label.

**Comment by danhermann** [comment] 2020-09-02 17:07
Thank you, @tsujan. I'll update when I'm able to try the 2.1.0 release.

**Comment by tsujan** [comment] 2021-08-06 16:45
Closing because it was never reproducible.

**Closed by tsujan** 2021-08-06 16:45 UTC
Labels: question

**Comment by chriswyatt** [comment] 2022-03-18 09:58
I'm having this problem too

**Comment by shlyakpavel** [comment] 2022-03-18 10:00
How do you reproduce it?
Please provide as much details as possible

**Comment by javier-fuentes** [comment] 2023-04-26 19:06
Same here, I recently switched my windows manager from Openbox to Kwin.

LXQt + Kwin + NixOS unstable
Qps 2.7.0 - A Visual Process Manager
Qt library 5.15.8
Linux WC 6.1.24  1-NixOS SMP PREEMPT_DYNAMIC [...] x86_64 GNU/Linux

**Comment by tsujan** [comment] 2023-04-26 20:04
> I recently switched my windows manager from Openbox to KWin.

That can't be related. I use KWin for years.

Please compile Qps from its latest source and run it from inside the compilation folder (no installation is needed) to see if happens again.

**Comment by javier-fuentes** [comment] 2023-11-01 16:23
Unfortunately this issue is always reproducible in my laptop running X and Wayland (I'm migrating from LxQt to Sway). When the process list goes blank and qps receives the focus again it closes showing this message:

DEBUG: version = 60160
Qps(0x1376c10, name="qps_main_window")
error marshalling arguments for create_pool: dup failed: Too many open files
Error marshalling request: Too many open files
The Wayland connection experienced a fatal error: Too many open files

A lot of years using LxQt. Thank you guys... 8')

**Comment by tsujan** [comment] 2023-11-01 16:35
> Error marshalling request: Too many open files

That may give us a clue. What is the output of
```
cat /proc/sys/fs/file-max
```
for you?

**Comment by javier-fuentes** [comment] 2023-11-01 22:37
```
cat /proc/sys/fs/file-max : 9223372036854775807
ulimit -Sn : 1024
ulimit -Hn : 524288
```
Anything else? ...

**Comment by tsujan** [comment] 2023-11-01 22:45
They're normal.

See this article, which explains how to find a process that may haven constantly opened files (but you don't need to touch your system settings): https://www.howtogeek.com/805629/too-many-open-files-linux/

**Comment by javier-fuentes** [comment] 2023-11-01 23:17
Thank you very much for your support tsujan

`$ lsof -p (qps.PID) | wc -l`

shows an incrisingly number of opened files before the crash. See list attached...

[lsof_qps.txt](https://github.com/lxqt/qps/files/13232537/lsof_qps.txt)

Does it ring a bell?

**Comment by tsujan** [comment] 2023-11-01 23:22
Please just use the command mentioned in that page, i.e.

```
lsof | awk '{ print $1 " " $2; }' | sort -rn | uniq -c | sort -rn | head -15
```

**Comment by tsujan** [comment] 2023-11-01 23:33
This is mine:

```
  45780 thunderbi 584535
  31941 falkon 900636
   6440 labwc 1265
   4978 qterminal 904171
   4420 WebExtens 584655
   4304 audacious 731105
   4237 featherpa 904022
   3838 waybar 1342
   3724 pcmanfm-q 246897
   3570 lxqt-poli 1346
   3388 QtWebEngi 900696
   3051 conky 1581
   2844 QtWebEngi 900871
   2838 lxqt-runn 2085
   2739 qps 904147
```

`qps` is the last one and normal, while `thunderbird` uses the largest amount of file handles (45780), but that's expected and normal too.

**Comment by javier-fuentes** [comment] 2023-11-01 23:39
Mine.

```
  24934 .firefox- 7652
   9955 .waybar-w 13067
   7864 .qps-wrap 17768
   3090 sway 7372
   1431 Isolated 12894
   1378 WebExtens 7815
   1325 Privilege 7768
   1325 Isolated 8064
   1325 Isolated 7900
   1325 Isolated 7896
   1325 Isolated 12049
   1325 Isolated 11828
   1325 Isolated 11674
   1325 Isolated 11604
   1325 Isolated 11571
```

**Comment by tsujan** [comment] 2023-11-01 23:43
What's `qps-wrap`? Its number seems normal, but why that `-wrap`?

And what's `Isolated`?

**Comment by javier-fuentes** [comment] 2023-11-01 23:48
Isolated web content in firefox I guess. I use Firefox with arkenfox settings and right now there are around fifteen opened tabs

**Comment by tsujan** [comment] 2023-11-01 23:55
> Isolated web content in firefox I guess.

Yes, it belongs to Firefox. `Isolated` seems suspicious to me. The `Isolated` instances shown here seem OK,  but if `Isolated` is repeated too many times, it may have exhausted file handles and caused "Too many open files".

Anyway, `qps` seems normal, although I don't understand that `-wrap` in your case. I'm using Wayland (LabWC).

**Comment by javier-fuentes** [comment] 2023-11-01 23:59
I'm using sway right now

**Comment by tsujan** [comment] 2023-11-02 00:07
Your file handles are exhausted by some process(es); hence "Too many open files". Your output does *not* show that it's `qps`.

**Comment by javier-fuentes** [comment] 2023-11-02 00:22
Perhaps I'm making a mistake here but I see things differently. When qps starts it's using 1200-1400 file handlers, but this number grows to 5000 after a couple of minutes and then 9200 and then crashes. This sounds not good.

Plus, the output of `lsof` shows that qps crashes when the number of opened files is a bit above 1000, I cannot say the number exactly.

**Comment by tsujan** [comment] 2023-11-02 00:46
> This sounds not good.

True. That's why https://github.com/lxqt/qps/issues/447 is open (its link is in this report too). My hope is that your output could shed some light on the situation later (also see https://github.com/lxqt/qps/issues/447#issuecomment-1703814124). Thanks!

**Comment by javier-fuentes** [comment] 2023-11-02 01:26
I've been reading the #447 thread and I think that both issues could be related or the same. Thanks tsujan and good luck hunting bugs

**Comment by tsujan** [comment] 2023-11-02 02:08
I think I've found an instance of `open()` without `close()` in the code of Qps, but I'm too sleepy to be sure. Tomorrow I'll make a PR (although it might not solve this enigma, it's needed).

**Comment by javier-fuentes** [comment] 2023-11-05 10:51
I think you've got it @tsujan :)
