### ISSUE TITLE
With "always on top" parents window are below on wayland

### ISSUE THREAD

**Issue by stefonarch** [lxqt/qps#474] opened 2024-05-20 20:39 UTC
Same goes for clicking on a process for details. As all of them are smaller they are hidden and only visible in the taskbar.
##### Expected Behavior

The confirmation window is always on top
##### Current Behavior

Killing a process with qps set to "above all windows" is tricky as the confirmation window is below.
##### Possible Solution

Use layer "overlay" under wayland for the confirmation window?
##### Steps to Reproduce (for bugs)

1. Set qps to "always on top"
2. Try to kill a process

**Comment by tsujan** [comment] 2024-05-20 20:56
> Killing a process with qps set to "above all windows" is tricky as the confirmation window is below.

If so, that's a problem in the Wayland WM. The confirmation dialog is a modal dialog and so, it should be placed over the main window by the WM.

We shouldn't add codes because of Wayland problems.

**Comment by tsujan** [comment] 2024-05-20 21:15
Closing because it's not specific to Qps.

**Closed by tsujan** 2024-05-20 21:15 UTC

**Comment by stefonarch** [comment] 2024-05-20 21:33
Actually it looks that kwin and wayfire get this right.

**Comment by stefonarch** [comment] 2024-05-20 21:39
Actually it looks that kwin only gets this right.

**Comment by tsujan** [comment] 2024-05-20 21:51
I all cases the problem is about not putting a modal dialog in front of its parent window. That should be fixed in the Wayland WM.
